### ISSUE TITLE
Model H617A Error

### ISSUE THREAD

**Issue by 0PandaDEV** [softgrass/govee-api-ble#7]
I ran this script on a Raspberry Pi 5

```py
from govee_api_ble import GoveeDevice

my_device = GoveeDevice("CA:39:32:35:48:4D")

my_device.setPower(False)

```

```
connect to CA:39:32:35:48:4D: Connection refused (111)
Traceback (most recent call last):
  File "/home/pandadev/Scripts/test/main.py", line 5, in <module>
    my_device.setPower(False)
  File "/home/pandadev/Scripts/test/venv/lib/python3.11/site-packages/govee_api_ble/device.py", line 39, in setPower
    output = subprocess.check_output("gatttool -i hci0 -b {} --char-write-req -a 0x0015 -n 3301000000000000000000000000000000000032".format(self.mac), shell=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gatttool -i hci0 -b CA:39:32:35:48:4D --char-write-req -a 0x0015 -n 3301000000000000000000000000000000000032' returned non-zero exit status 1.
```

**Comment by softgrass** [comment]
Hi! If you read in your error it says
`connect to CA:39:32:35:48:4D: Connection refused (111)`
This means your device is either not on, not discoverable, or the MAC address is wrong. This is an issue with your device, not the API

**Comment by 0PandaDEV** [comment]
Ok I found out something very strange your library or my pi/gatttool cannot connect to my light strip, but I tried the exact same with a homebridge setup and there it seems to work for some reason also when I use the `bluetoothctl` I can connect to the device, but I get disconnected from it after 5 second.

![Tabby_N4wLwiMSCd](https://github.com/softgrass/govee-api-ble/assets/70103896/1ec6c31e-c3ff-4ce2-8dcf-691c0a0da0a1)
